### PR TITLE
Support for measter item measure formats

### PR DESCRIPTION
**Pull request by hgrpixum**

### CODE REVIEW

**Comment by hgrpixum** [comment]
i have added the functionality to export and import master item measure formats in my fork of the repo

**Comment by hgrpixum** [comment]
#17

**Comment by maxwellginqo** [comment]
Hello, I tested your commit and it looks like it broke the Synchronize Measure functionality. Was it working on your side before committing? Which version of Qlik Sense did you test with? - we used February 2022 SR1.

Thanks,
Maxwell.

**Comment by GINQO** [comment]
2022-06-08 (RS) - Implemented this code into the Master Repo

**Pull request closed without merging**
